version: '3.8'

services:
  # Node.js Application
  app:
    build: .
    container_name: nodejs-app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - mongo

  # MongoDB
  mongo:
    image: mongo:latest
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

volumes:
  mongo-data:
